# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - run: dotnet --info

    - name: Build and test (win)
      run: ./build ci
      shell: cmd
      if: ${{ runner.os == 'Windows' }} 
      
      ## Only difference here is not forcing cmd
    - name: Build and test (!win)
      run: ./build ci
      if: ${{ runner.os != 'Windows' }}
